name: tests

on: [push, pull_request]

jobs:
  integration-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Run INTEGRATION tests
        run: |
          make
          make t-integration

  unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Install dependencies
        run: sudo apt-get install -y libavformat-dev libavcodec-dev libavutil-dev libswscale-dev libswresample-dev libsdl2-dev

      - name: Run INTEGRATION tests
        run: |
          export SDL_AUDIODRIVER=dummy
          make
          make t-unit
