name: CI/CD

on: [push, pull_request]

jobs:
  linux-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y libavformat-dev libavcodec-dev libavutil-dev \
            libswscale-dev libswresample-dev libsdl2-dev

      - name: Build app (Linux)
        run: make

  macos-build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Homebrew (macOS)
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zshrc
          echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.bashrc
          eval "$(/opt/homebrew/bin/brew shellenv)"

      - name: Install dependencies (macOS)
        run: |
          brew update
          brew install sdl2 ffmpeg
      
      - name: Build app (macOS)
        run: make
  windows-build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (Windows)
        run: |
          choco install msys2 --params="/NoUpdate" -y
          Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
          refreshenv

      - name: First-stage update (allow restart)
        run: |
          C:\tools\msys64\usr\bin\bash.exe -l -c "
          pacman --noconfirm -Syuu || echo 'MSYS2 update completed (session terminated)' >&2
          "
          exit 0  # Always succeed this step
      - name: Install packages in fresh session
        run: |
          # Install ONLY the essential packages
          C:\tools\msys64\usr\bin\bash.exe -l -c "
            pacman -S --needed --noconfirm \
              mingw-w64-x86_64-make \
              mingw-w64-x86_64-gcc \
              mingw-w64-x86_64-SDL2 \
              mingw-w64-x86_64-pkg-config \
              mingw-w64-x86_64-avcodec \
              mingw-w64-x86_64-avformat \
              mingw-w64-x86_64-avutil \
              mingw-w64-x86_64-swscale
          "

      - name: Verify installation
        run: |
          C:\tools\msys64\usr\bin\bash.exe -l -c "
            echo '=== Installed packages ==='
            pacman -Q | grep mingw-w64-x86_64
            
            echo '=== Files in /mingw64/bin ==='
            ls /mingw64/bin/make.exe /mingw64/bin/gcc.exe
            
            echo '=== Make version ==='
            /mingw64/bin/make.exe --version || echo 'Make not found'
          "

      - name: Build project
        run: |
          C:\tools\msys64\usr\bin\bash.exe -l -c "
            # Force MinGW environment
            export MSYSTEM=MINGW64
            source /etc/profile
            
            # Use absolute path to make
            if [ -f /mingw64/bin/make.exe ]; then
              echo '=== Building with make ==='
              /mingw64/bin/make.exe
            else
              echo 'ERROR: make.exe not found in /mingw64/bin'
              echo 'Installed packages containing make:'
              pacman -Ql | grep make.exe
              exit 1
            fi
          "
