name: CI/CD

on:
  push:
    branches: [ "master", "cicd" ]
  pull_request:
    branches: [ "master", "cicd" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t my-c-project .

      - name: Run Docker Container and Build
        run: docker run --rm -v $(pwd):/app my-c-project make
      
      - name: Create Windows Binaries Directory
        if: runner.os == 'Linux'
        run: mkdir -p windows_binaries
      
      - name: Copy Windows Executable
        if: runner.os == 'Linux'
        run: cp video_viewer.exe windows_binaries/video_viewer.exe
      
      - name: Upload Windows Executable
        uses: actions/upload-artifact@v3
        with:
          name: windows_executable
          path: windows_binaries
