name: ci

on: [push, pull_request]

jobs:
  linux-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y libavformat-dev libavcodec-dev libavutil-dev \
            libswscale-dev libswresample-dev libsdl2-dev

      - name: Build app (Linux)
        run: make

  macos-build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Homebrew (macOS)
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zshrc
          echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.bashrc
          eval "$(/opt/homebrew/bin/brew shellenv)"

      - name: Install dependencies (macOS)
        run: |
          brew update
          brew install sdl2 ffmpeg
      
      - name: Build app (macOS)
        run: make

  windows-build:
    runs-on: windows-latest
    env:
      MSYS2_ROOT: C:\tools\msys64
      CACHE_VERSION: v1

    steps:
      - uses: actions/checkout@v4

      - name: Cache MSYS2 packages
        uses: actions/cache@v3
        id: msys2-cache
        with:
          path: |
            ${{ env.MSYS2_ROOT }}\var\cache\pacman\pkg
            ${{ env.MSYS2_ROOT }}\mingw64
          key: msys2-${{ runner.os }}-${{ env.CACHE_VERSION }}
          restore-keys: |
            msys2-${{ runner.os }}-

      - name: Show cache status
        run: |
          echo "Cache hit: ${{ steps.msys2-cache.outputs.cache-hit }}"
          echo "Cache key: ${{ steps.msys2-cache.outputs.cache-primary-key }}"

      - name: Setup MSYS2 (cache miss only)
        if: steps.msys2-cache.outputs.cache-hit != 'true'
        run: |
          choco install msys2 --params="/NoUpdate" -y
          Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
          refreshenv

          "%MSYS2_ROOT%\usr\bin\bash.exe" --login -c "
          pacman --noconfirm -Syuu || echo 'MSYS2 update completed (session terminated)' >&2
          "
          exit 0

      - name: Install packages (cache miss only)
        if: steps.msys2-cache.outputs.cache-hit != 'true'
        run: |
          "%MSYS2_ROOT%\usr\bin\bash.exe" -l -c "
            pacman -S --needed --noconfirm \
              mingw-w64-x86_64-make \
              mingw-w64-x86_64-gcc \
              mingw-w64-x86_64-SDL2 \
              mingw-w64-x86_64-pkg-config \
              mingw-w64-x86_64-ffmpeg
          "

      - name: Build project
        shell: cmd
        run: |
          call "%MSYS2_ROOT%\usr\bin\bash.exe" --login -c "set -x && \
                export MSYSTEM=MINGW64 && \
                source /etc/profile && \
                uname
                "
