name: ci

on: [push, pull_request]

jobs:
  linux-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y libavformat-dev libavcodec-dev libavutil-dev \
            libswscale-dev libswresample-dev libsdl2-dev

      - name: Build app (Linux)
        run: |
          export SDL_AUDIODRIVER=dummy
          make
          make t-integration
          make t-unit

  macos-build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Homebrew (macOS)
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zshrc
          echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.bashrc
          eval "$(/opt/homebrew/bin/brew shellenv)"

      - name: Install dependencies (macOS)
        run: |
          brew update
          brew install sdl2 ffmpeg
      
      - name: Build app (macOS)
        run: |
          export SDL_AUDIODRIVER=dummy
          make
          make t-integration
          make t-unit

  windows-build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: mingw-w64-x86_64-make mingw-w64-x86_64-gcc mingw-w64-x86_64-SDL2 mingw-w64-x86_64-pkg-config mingw-w64-x86_64-ffmpeg
          update: true

      - name: Verify installation
        shell: msys2 {0}
        run: |
          export SDL_AUDIODRIVER=dummy
          mingw32-make all 
          mingw32-make t-integration
          mingw32-make t-unit
