name: Release

on:
  push:
    tags:
      - 'v*'
    branches: [ release ]

jobs:
  release-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Read changelog
        description: Changelog is a description of changes between releases.
        id: changelog
        run: echo "changelog<<EOF" >> $GITHUB_ENV && cat CHANGELOG.md >> $GITHUB_ENV && echo "EOF"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ env.changelog }}
          draft: false
          prerelease: false
