name: Build with Local Libs

on: [ push ]

jobs:
  libs-build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libavformat-dev libavcodec-dev libavutil-dev \
          libswscale-dev libswresample-dev libsdl2-dev

      - name: Build video_viewer
        run: |
          mkdir -p libs
          gcc -o video_viewer src/*.c \
          -lavformat -lavcodec -lavutil -lswscale -lswresample -lSDL2 \
          -Wl,-rpath='$ORIGIN/libs'

      - name: Bundle all required libraries
        run: |
          # Create libs directory if not exists
          mkdir -p libs
          
          # Get all dependencies excluding system libraries
          ldd video_viewer | awk '/=> \// {print $3}' | \
          grep -vE "libc.so.6|libpthread.so.0|libm.so.6|libdl.so.2|ld-linux-x86-64.so.2" | \
          xargs -I{} cp -v {} libs/
          
          # Use patchelf to set the correct rpath
          patchelf --set-rpath '$ORIGIN/libs' video_viewer
          
          # Make all copied libraries executable
          chmod +x libs/*
          
          # Verify all dependencies are resolved
          ldd video_viewer || true
          readelf -d video_viewer | grep RPATH || true

      - name: Create portable bundle
        run: |
          # Create a self-contained directory structure
          mkdir -p video_viewer_bundle
          cp video_viewer video_viewer_bundle/
          cp -r libs video_viewer_bundle/
          
          # Create a wrapper script
          echo '#!/bin/sh
          SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
          export LD_LIBRARY_PATH="$SCRIPT_DIR/libs:$LD_LIBRARY_PATH"
          exec "$SCRIPT_DIR/video_viewer" "$@"' > video_viewer_bundle/run.sh
          
          chmod +x video_viewer_bundle/run.sh
          
          # Create archive
          tar czvf video_viewer_bundle.tar.gz video_viewer_bundle/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: video_viewer_portable
          path: video_viewer_bundle.tar.gz
