name: Build with Local Libs

on: [ push ]

jobs:
  libs-build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libavformat-dev libavcodec-dev libavutil-dev \
          libswscale-dev libswresample-dev libsdl2-dev patchelf

      - name: Build video_viewer
        run: |
          mkdir -p libs
          gcc -o video_viewer.bin src/*.c \
          -lavformat -lavcodec -lavutil -lswscale -lswresample -lSDL2 \
          -Wl,-rpath='$ORIGIN/libs'

      - name: Bundle all required libraries
        run: |
          mkdir -p libs
          ldd video_viewer.bin | awk '/=> \// {print $3}' | \
          grep -vE "libc.so.6|libpthread.so.0|libm.so.6|libdl.so.2|ld-linux-x86-64.so.2" | \
          xargs -I{} cp -v {} libs/
          
          patchelf --set-rpath '$ORIGIN/libs' video_viewer.bin
          chmod +x libs/*

      - name: Create portable command
        run: |
          # Create wrapper script that will be the main executable
          echo '#!/bin/sh
          SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
          export LD_LIBRARY_PATH="$SCRIPT_DIR/libs:$LD_LIBRARY_PATH"
          exec "$SCRIPT_DIR/video_viewer.bin" "$@"' > video_viewer
          
          chmod +x video_viewer
          
          # Create directory structure
          mkdir -p video_viewer_pkg
          mv video_viewer video_viewer.bin libs video_viewer_pkg/
          
          # Create archive
          tar czvf video_viewer.tar.gz video_viewer_pkg/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: video_viewer_command
          path: video_viewer.tar.gz
