name: linter(C)

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y clang-tidy
          sudo apt-get install -y libavformat-dev libavcodec-dev libavutil-dev libswscale-dev libswresample-dev libsdl2-dev

      - name: Run clang-tidy
        run: |
          clang-tidy --version
          clang-tidy src/*.c -- -Iinclude
