name: INTEGRATION tests

on:
  push:
    branches: [ "master", "cicd", "cicd-kek" ]
  pull_request:
    branches: [ "master", "cicd", "cicd-kek" ]

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: apt-get install -y libavformat-dev libavcodec-dev libavutil-dev libswscale-dev libswresample-dev

      - name: Run INTEGRATION tests
        run: |
          make
          make t-integration
